version: '3.1'

services:
  medical_center_db:
    image: mysql:8.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command: 
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-files:/var/lib/mysql-files
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data:
