version: "3.9"
services:
  master:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd"
    ports:
      - "5450:5432"
    networks:
      - postgres
  replica:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd"
    ports:
      - "5451:5432"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge